export const ROLES = [
  { id: 'student', label: 'Student' },
  { id: 'researcher', label: 'Researcher' },
  { id: 'founder', label: 'Founder' },
  { id: 'pm', label: 'PM' },
  { id: 'analyst', label: 'Analyst' },
  { id: 'designer', label: 'Designer' },
  { id: 'marketer', label: 'Marketer' },
  { id: 'developer', label: 'Developer' },
  { id: 'consultant', label: 'Consultant' },
];

export const BUDGETS = [
  { id: 'free', label: 'Free only', max: 0 },
  { id: 'under500', label: 'Under ₹500', max: 500 },
  { id: 'mid', label: '₹500–₹2,000', max: 2000 },
  { id: 'high', label: '₹2,000+', max: 999999 },
];

export const PRIORITIES = [
  { id: 'best-output', label: 'Best output' },
  { id: 'cheapest', label: 'Cheapest' },
  { id: 'fastest', label: 'Fastest' },
  { id: 'privacy-first', label: 'Privacy first' },
];

export const FEATURES = [
  { id: 'image-gen', label: 'Image generation' },
  { id: 'agents', label: 'Workflow automation / agents' },
  { id: 'long-context', label: 'Long context' },
  { id: 'token-efficiency', label: 'Token efficiency' },
  { id: 'integrations', label: 'Integrations / collabs' },
];

export const TOOLS = [
  { id: 'chatgpt-plus', name: 'ChatGPT Plus', category: 'llm', tagline: 'Strong general-purpose assistant.', useCases: ['writing','coding','analysis','brainstorming','presentation'], bestForRoles: ['student','founder','pm','analyst','marketer','consultant'], strengths: ['Balanced for everyday work','Good multimodal support','Broad ecosystem'], weaknesses: ['Intl card needed','Can burn tokens on long sessions'], priceInrMonth: 1700, priceApprox: true, indiaPaymentSupport: 'workaround', indiaNotes: 'International card usually needed.', contextLengthK: 128, tokenExhaustionRisk: 'medium', imageGen: true, agentWorkflow: true, longContext: true, integrations: ['canva','notion','zapier'], collabSupport: true, privacyLevel: 'low', speed: 'fast', outputQuality: 'high', sourceUrl: 'https://chatgpt.com/' },
  { id: 'claude-pro', name: 'Claude Pro', category: 'llm', tagline: 'Best for deep reading and long docs.', useCases: ['writing','research','analysis','long-context','coding'], bestForRoles: ['researcher','analyst','pm','consultant','student'], strengths: ['Excellent long-context reasoning','Clean writing and summaries','Very strong for PDFs'], weaknesses: ['Intl card needed','Token burn can happen fast'], priceInrMonth: 1600, priceApprox: true, indiaPaymentSupport: 'workaround', indiaNotes: 'International card usually needed.', contextLengthK: 200, tokenExhaustionRisk: 'high', imageGen: false, agentWorkflow: false, longContext: true, integrations: ['notion','perplexity','slack'], collabSupport: false, privacyLevel: 'low', speed: 'fast', outputQuality: 'top', sourceUrl: 'https://claude.ai/' },
  { id: 'gemini-advanced', name: 'Gemini Advanced', category: 'llm', tagline: 'Best value in Google ecosystem.', useCases: ['writing','analysis','research','presentation','brainstorming'], bestForRoles: ['student','analyst','pm','marketer','consultant'], strengths: ['Native India payment support','Strong long context','Fast for daily use'], weaknesses: ['Answer style can be generic','Less polished for some workflows'], priceInrMonth: 1950, priceApprox: true, indiaPaymentSupport: 'native', indiaNotes: 'UPI-friendly via Google billing in many cases.', contextLengthK: 1000, tokenExhaustionRisk: 'low', imageGen: true, agentWorkflow: true, longContext: true, integrations: ['google-drive','gmail','docs'], collabSupport: true, privacyLevel: 'low', speed: 'fast', outputQuality: 'high', sourceUrl: 'https://gemini.google.com/' },
  { id: 'google-ai-studio', name: 'Google AI Studio', category: 'llm', tagline: 'Free playground for Gemini models.', useCases: ['coding','analysis','brainstorming','research'], bestForRoles: ['student','developer','analyst','researcher'], strengths: ['Free to start','Fast experimentation','Easy prompt testing'], weaknesses: ['Less polished product feel','Not a full premium assistant'], priceInrMonth: 0, priceApprox: false, indiaPaymentSupport: 'native', indiaNotes: 'Free tier, easy access.', contextLengthK: 1000, tokenExhaustionRisk: 'low', imageGen: false, agentWorkflow: false, longContext: true, integrations: ['google-drive','docs'], collabSupport: false, privacyLevel: 'low', speed: 'fast', outputQuality: 'good', sourceUrl: 'https://aistudio.google.com/' },
  { id: 'perplexity-pro', name: 'Perplexity Pro', category: 'search-research', tagline: 'Best for cited research and live web grounding.', useCases: ['research','analysis','writing','long-context'], bestForRoles: ['researcher','consultant','analyst','student','pm'], strengths: ['Fast research with citations','Great for market scans','Good web grounding'], weaknesses: ['Intl card needed','Not ideal as lone creative writer'], priceInrMonth: 1600, priceApprox: true, indiaPaymentSupport: 'workaround', indiaNotes: 'International card usually needed.', contextLengthK: 50, tokenExhaustionRisk: 'medium', imageGen: false, agentWorkflow: false, longContext: false, integrations: ['notion','google-drive','slack'], collabSupport: false, privacyLevel: 'low', speed: 'fast', outputQuality: 'high', sourceUrl: 'https://www.perplexity.ai/' },
  { id: 'phind', name: 'Phind', category: 'search-research', tagline: 'Developer-friendly AI search.', useCases: ['coding','research','analysis'], bestForRoles: ['developer','student','researcher'], strengths: ['Great for coding questions','Fast answers','Useful docs grounding'], weaknesses: ['Lower polish than premium suites','Can overlap with other search tools'], priceInrMonth: 1600, priceApprox: true, indiaPaymentSupport: 'workaround', indiaNotes: 'International card required for premium.', contextLengthK: 32, tokenExhaustionRisk: 'medium', imageGen: false, agentWorkflow: false, longContext: false, integrations: ['github','slack'], collabSupport: false, privacyLevel: 'low', speed: 'fast', outputQuality: 'high', sourceUrl: 'https://www.phind.com/' },
  { id: 'you-com', name: 'You.com', category: 'search-research', tagline: 'Search + assistant hybrid.', useCases: ['research','writing','analysis'], bestForRoles: ['student','analyst','consultant'], strengths: ['Search-first workflows','Good for quick comparisons','Broad assistant modes'], weaknesses: ['Pricing can feel fuzzy','Not best-in-class for deep writing'], priceInrMonth: 1300, priceApprox: true, indiaPaymentSupport: 'workaround', indiaNotes: 'International card generally needed.', contextLengthK: 32, tokenExhaustionRisk: 'medium', imageGen: false, agentWorkflow: false, longContext: false, integrations: ['slack','notion'], collabSupport: false, privacyLevel: 'low', speed: 'fast', outputQuality: 'good', sourceUrl: 'https://you.com/' },
  { id: 'notion-ai', name: 'Notion AI', category: 'productivity', tagline: 'Best for notes, docs, and knowledge base.', useCases: ['writing','analysis','presentation','planning'], bestForRoles: ['student','pm','founder','analyst','consultant'], strengths: ['Great for structured docs','Knowledge-base friendly','Useful inside a workflow'], weaknesses: ['Not a standalone power model','Can feel limited alone'], priceInrMonth: 1200, priceApprox: true, indiaPaymentSupport: 'workaround', indiaNotes: 'Usually paid via international card.', contextLengthK: 20, tokenExhaustionRisk: 'medium', imageGen: false, agentWorkflow: false, longContext: false, integrations: ['slack','gmail','google-drive'], collabSupport: true, privacyLevel: 'medium', speed: 'fast', outputQuality: 'good', sourceUrl: 'https://www.notion.so/product/ai' },
  { id: 'gamma', name: 'Gamma', category: 'productivity', tagline: 'Fast decks and presentation drafts.', useCases: ['presentation','writing','design'], bestForRoles: ['student','pm','marketer','consultant'], strengths: ['Quick presentation output','Nice visual formatting','Good for pitch decks'], weaknesses: ['Not deep content reasoning','Limited for research-heavy tasks'], priceInrMonth: 800, priceApprox: true, indiaPaymentSupport: 'workaround', indiaNotes: 'Payment friction can appear.', contextLengthK: 12, tokenExhaustionRisk: 'low', imageGen: false, agentWorkflow: false, longContext: false, integrations: ['google-drive','notion'], collabSupport: true, privacyLevel: 'medium', speed: 'fast', outputQuality: 'good', sourceUrl: 'https://gamma.app/' },
  { id: 'canva', name: 'Canva Magic Studio', category: 'image-gen', tagline: 'Best for marketing assets and quick visuals.', useCases: ['design','presentation','image-gen'], bestForRoles: ['designer','marketer','student','founder','pm'], strengths: ['Huge template ecosystem','Easy design workflow','Collaboration-friendly'], weaknesses: ['Not ideal for deep AI reasoning','Feature overlap with other design tools'], priceInrMonth: 500, priceApprox: true, indiaPaymentSupport: 'native', indiaNotes: 'Strong India billing support.', contextLengthK: null, tokenExhaustionRisk: 'none', imageGen: true, agentWorkflow: false, longContext: false, integrations: ['google-drive','slack','notion'], collabSupport: true, privacyLevel: 'medium', speed: 'fast', outputQuality: 'high', sourceUrl: 'https://www.canva.com/' },
  { id: 'midjourney', name: 'Midjourney', category: 'image-gen', tagline: 'Best output for creative image generation.', useCases: ['design','image-gen'], bestForRoles: ['designer','marketer','founder'], strengths: ['Beautiful image quality','Great creative control','Strong style consistency'], weaknesses: ['Intl card needed','Not ideal for quick business graphics'], priceInrMonth: 850, priceApprox: true, indiaPaymentSupport: 'workaround', indiaNotes: 'Usually requires international payment method.', contextLengthK: null, tokenExhaustionRisk: 'none', imageGen: true, agentWorkflow: false, longContext: false, integrations: ['discord','canva'], collabSupport: false, privacyLevel: 'low', speed: 'medium', outputQuality: 'top', sourceUrl: 'https://www.midjourney.com/' },
  { id: 'adobe-firefly', name: 'Adobe Firefly', category: 'image-gen', tagline: 'Safer, business-friendly image generation.', useCases: ['design','image-gen','presentation'], bestForRoles: ['designer','marketer','student'], strengths: ['Native India support','Strong for branded assets','Commercially safer posture'], weaknesses: ['Less artistic than Midjourney','Limited compared to full creative suites'], priceInrMonth: 0, priceApprox: false, indiaPaymentSupport: 'native', indiaNotes: 'Free tier available; paid plan varies.', contextLengthK: null, tokenExhaustionRisk: 'none', imageGen: true, agentWorkflow: false, longContext: false, integrations: ['canva','creative-cloud'], collabSupport: true, privacyLevel: 'medium', speed: 'fast', outputQuality: 'high', sourceUrl: 'https://www.adobe.com/products/firefly.html' },
  { id: 'runway', name: 'Runway Gen-3', category: 'image-gen', tagline: 'Video and motion generation.', useCases: ['design','image-gen'], bestForRoles: ['designer','marketer','founder'], strengths: ['Great for motion assets','Strong demo value','Creative workflows'], weaknesses: ['Higher cost','Not needed for most business stacks'], priceInrMonth: 1250, priceApprox: true, indiaPaymentSupport: 'workaround', indiaNotes: 'Usually international card required.', contextLengthK: null, tokenExhaustionRisk: 'none', imageGen: true, agentWorkflow: false, longContext: false, integrations: ['canva'], collabSupport: false, privacyLevel: 'low', speed: 'slow', outputQuality: 'high', sourceUrl: 'https://runwayml.com/' },
  { id: 'cursor', name: 'Cursor', category: 'builder', tagline: 'AI coding editor for product builders.', useCases: ['coding','builder','analysis'], bestForRoles: ['developer','founder','student','analyst'], strengths: ['Excellent coding workflow','Fast iteration','Great GitHub fit'], weaknesses: ['Can duplicate LLM spend','Needs good prompts'], priceInrMonth: 1650, priceApprox: true, indiaPaymentSupport: 'workaround', indiaNotes: 'Intl card usually required.', contextLengthK: 64, tokenExhaustionRisk: 'medium', imageGen: false, agentWorkflow: true, longContext: true, integrations: ['github','vercel','notion'], collabSupport: false, privacyLevel: 'low', speed: 'fast', outputQuality: 'high', sourceUrl: 'https://cursor.com/' },
  { id: 'lovable', name: 'Lovable', category: 'builder', tagline: 'Fast app builder for product demos.', useCases: ['builder','presentation','coding'], bestForRoles: ['founder','pm','student','designer'], strengths: ['Very fast prototyping','Great for startup demos','Useful for portfolio projects'], weaknesses: ['Less control than full code','Can feel generic if overused'], priceInrMonth: 1800, priceApprox: true, indiaPaymentSupport: 'workaround', indiaNotes: 'Pricing may vary by plan.', contextLengthK: 64, tokenExhaustionRisk: 'medium', imageGen: false, agentWorkflow: true, longContext: false, integrations: ['github','supabase','vercel'], collabSupport: false, privacyLevel: 'low', speed: 'fast', outputQuality: 'high', sourceUrl: 'https://lovable.dev/' },
  { id: 'bolt', name: 'Bolt.new', category: 'builder', tagline: 'Quick web app builder.', useCases: ['builder','coding','presentation'], bestForRoles: ['student','founder','developer','designer'], strengths: ['Very fast MVPs','Good for landing pages','Simple onboarding'], weaknesses: ['Not ideal for complex logic','Can overlap with Lovable'], priceInrMonth: 1650, priceApprox: true, indiaPaymentSupport: 'workaround', indiaNotes: 'Intl card likely needed.', contextLengthK: 64, tokenExhaustionRisk: 'medium', imageGen: false, agentWorkflow: true, longContext: false, integrations: ['github','vercel'], collabSupport: false, privacyLevel: 'low', speed: 'fast', outputQuality: 'high', sourceUrl: 'https://bolt.new/' },
  { id: 'v0', name: 'v0 by Vercel', category: 'builder', tagline: 'UI generator for clean frontends.', useCases: ['builder','design','coding'], bestForRoles: ['developer','designer','pm'], strengths: ['Very clean UI output','Best for frontend scaffolds','Pairs well with GitHub'], weaknesses: ['Less end-to-end than builders','Can overfit to UI only'], priceInrMonth: 1650, priceApprox: true, indiaPaymentSupport: 'workaround', indiaNotes: 'Intl card usually needed.', contextLengthK: 32, tokenExhaustionRisk: 'medium', imageGen: false, agentWorkflow: false, longContext: false, integrations: ['github','vercel'], collabSupport: false, privacyLevel: 'low', speed: 'fast', outputQuality: 'high', sourceUrl: 'https://v0.dev/' },
  { id: 'replit', name: 'Replit', category: 'builder', tagline: 'Quick build-and-run app platform.', useCases: ['builder','coding'], bestForRoles: ['student','developer','founder'], strengths: ['Fast prototyping','Easy deployment','Hands-on coding workflow'], weaknesses: ['Not the cleanest UI output','Can be overkill for simple demo sites'], priceInrMonth: 1600, priceApprox: true, indiaPaymentSupport: 'workaround', indiaNotes: 'May require international payment method.', contextLengthK: 64, tokenExhaustionRisk: 'medium', imageGen: false, agentWorkflow: true, longContext: false, integrations: ['github','vercel'], collabSupport: true, privacyLevel: 'low', speed: 'fast', outputQuality: 'good', sourceUrl: 'https://replit.com/' },
  { id: 'github-copilot', name: 'GitHub Copilot', category: 'builder', tagline: 'Coding assistant inside IDE and GitHub.', useCases: ['coding','builder'], bestForRoles: ['developer','student','analyst'], strengths: ['Best for code completion','Fits GitHub workflows','Low friction for devs'], weaknesses: ['Not a full product tool','Less useful outside code'], priceInrMonth: 900, priceApprox: true, indiaPaymentSupport: 'native', indiaNotes: 'Often easier billing than many US tools.', contextLengthK: 32, tokenExhaustionRisk: 'medium', imageGen: false, agentWorkflow: false, longContext: false, integrations: ['github','vs-code'], collabSupport: false, privacyLevel: 'medium', speed: 'fast', outputQuality: 'high', sourceUrl: 'https://github.com/features/copilot' },
  { id: 'n8n', name: 'n8n', category: 'automation', tagline: 'Powerful workflow automation and agents.', useCases: ['automation','agents','integration'], bestForRoles: ['founder','pm','developer','analyst'], strengths: ['Great for automations','Self-hostable','Flexible workflows'], weaknesses: ['Needs setup','Not plug-and-play for everyone'], priceInrMonth: 0, priceApprox: false, indiaPaymentSupport: 'native', indiaNotes: 'Self-hosted free option.', contextLengthK: null, tokenExhaustionRisk: 'none', imageGen: false, agentWorkflow: true, longContext: false, integrations: ['slack','notion','google-drive','gmail'], collabSupport: false, privacyLevel: 'high', speed: 'fast', outputQuality: 'good', sourceUrl: 'https://n8n.io/' },
  { id: 'make', name: 'Make', category: 'automation', tagline: 'Visual workflow automation.', useCases: ['automation','agents','integration'], bestForRoles: ['founder','pm','marketer','analyst'], strengths: ['Very visual builder','Good app integrations','Fast to understand'], weaknesses: ['Can become expensive','Workflows can get messy'], priceInrMonth: 800, priceApprox: true, indiaPaymentSupport: 'workaround', indiaNotes: 'Billing friction common.', contextLengthK: null, tokenExhaustionRisk: 'none', imageGen: false, agentWorkflow: true, longContext: false, integrations: ['slack','notion','google-drive','gmail'], collabSupport: true, privacyLevel: 'medium', speed: 'fast', outputQuality: 'good', sourceUrl: 'https://www.make.com/' },
  { id: 'zapier', name: 'Zapier', category: 'automation', tagline: 'Broadest app automation coverage.', useCases: ['automation','agents','integration'], bestForRoles: ['founder','pm','marketer','consultant'], strengths: ['Huge app catalog','Easy to start','Great for quick ops'], weaknesses: ['Gets costly quickly','Less control than n8n'], priceInrMonth: 1650, priceApprox: true, indiaPaymentSupport: 'workaround', indiaNotes: 'Intl card generally needed.', contextLengthK: null, tokenExhaustionRisk: 'none', imageGen: false, agentWorkflow: true, longContext: false, integrations: ['slack','notion','google-drive','gmail'], collabSupport: true, privacyLevel: 'medium', speed: 'fast', outputQuality: 'good', sourceUrl: 'https://zapier.com/' },
  { id: 'otter', name: 'Otter.ai', category: 'productivity', tagline: 'Meeting notes and transcription.', useCases: ['analysis','writing','presentation'], bestForRoles: ['pm','consultant','founder','analyst'], strengths: ['Strong transcription','Useful for interviews and meetings','Fast summaries'], weaknesses: ['Not a core planner tool','Limited decision support'], priceInrMonth: 650, priceApprox: true, indiaPaymentSupport: 'workaround', indiaNotes: 'Pricing varies by plan.', contextLengthK: 8, tokenExhaustionRisk: 'low', imageGen: false, agentWorkflow: false, longContext: false, integrations: ['notion','google-drive'], collabSupport: true, privacyLevel: 'medium', speed: 'fast', outputQuality: 'good', sourceUrl: 'https://otter.ai/' },
  { id: 'ollama', name: 'Ollama', category: 'local-privacy', tagline: 'Run models locally on your machine.', useCases: ['privacy','coding','analysis','research'], bestForRoles: ['developer','researcher','analyst'], strengths: ['Local privacy','No recurring cost','Great for experimentation'], weaknesses: ['Requires setup and hardware','Lower polish than hosted tools'], priceInrMonth: 0, priceApprox: false, indiaPaymentSupport: 'native', indiaNotes: 'Free local tool.', contextLengthK: 8, tokenExhaustionRisk: 'none', imageGen: false, agentWorkflow: false, longContext: false, integrations: ['github','n8n'], collabSupport: false, privacyLevel: 'high', speed: 'medium', outputQuality: 'good', sourceUrl: 'https://ollama.com/' },
  { id: 'obsidian', name: 'Obsidian', category: 'productivity', tagline: 'Local knowledge base for serious notes.', useCases: ['writing','research','analysis','privacy'], bestForRoles: ['researcher','student','analyst','consultant'], strengths: ['Local-first notes','Great knowledge management','Good for long-term thinking'], weaknesses: ['Not an AI assistant by itself','Requires workflow discipline'], priceInrMonth: 0, priceApprox: false, indiaPaymentSupport: 'native', indiaNotes: 'Free for personal use.', contextLengthK: null, tokenExhaustionRisk: 'none', imageGen: false, agentWorkflow: false, longContext: false, integrations: ['notion','github'], collabSupport: false, privacyLevel: 'high', speed: 'fast', outputQuality: 'good', sourceUrl: 'https://obsidian.md/' },
];

export const BUNDLE_RECIPE_DEFS = [
  { id: 'best-overall', label: 'Best overall', strategy: 'best overall', description: 'Balanced quality + fit + India friction.' },
  { id: 'cheapest', label: 'Cheapest', strategy: 'cheap', description: 'Best for low spend and free tiers.' },
  { id: 'fastest', label: 'Fastest', strategy: 'fast', description: 'Fastest to start and fastest to ship.' },
  { id: 'best-output', label: 'Best output', strategy: 'output', description: 'Highest quality for the use case.' },
  { id: 'privacy-first', label: 'Privacy first', strategy: 'privacy', description: 'Local or high-privacy options first.' },
  { id: 'builders', label: 'Best for builders', strategy: 'builder', description: 'Great for app creation and demos.' },
  { id: 'research', label: 'Best for researchers', strategy: 'research', description: 'Long docs, citations, and structured reading.' },
  { id: 'design', label: 'Best for designers', strategy: 'design', description: 'Visual assets and polished creative output.' },
];
